<a href="https://colab.research.google.com/github/Oswaldoivann/Sars-Cov-2/blob/main/TRANSFORMACION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

# TRANSFORMAMOS NUESTRA BASE DE DATOS

In [ ]:
# IMPORTACION DE CSV DESDE COLAB 

#from google.colab import drive
#drive.mount('/content/drive')
#df = pd.read_csv('/content/drive/MyDrive/DATOS/COVID19MEXICO.csv')

In [ ]:
# IMPORTACION DE CSV DESDE LOCAL EN JUPYTER
df = pd.read_csv(r'C:\Users\oswal\Documents\datos_abiertos_covid19\COVID19MEXICO.csv',
                 header=0,
                 parse_dates=['FECHA_ACTUALIZACION', 'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF'])

C:\Users\oswal\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (38) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [ ]:
df.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'INDIGENA',
       'DIABETES', 'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'TOMA_MUESTRA_LAB', 'RESULTADO_LAB',
       'TOMA_MUESTRA_ANTIGENO', 'RESULTADO_ANTIGENO', 'CLASIFICACION_FINAL',
       'MIGRANTE', 'PAIS_NACIONALIDAD', 'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [ ]:
df.shape

(11808599, 40)

In [ ]:
df.head()

FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  SECTOR  ENTIDAD_UM  SEXO  \
0          2021-11-26      z4e838       1      12           9     2   
1          2021-11-26      z2b144       2      12           9     1   
2          2021-11-26      zz7202       1      12          16     2   
3          2021-11-26      z58ed3       2      12          18     1   
4          2021-11-26      z3be8c       2      12           7     1   

   ENTIDAD_NAC  ENTIDAD_RES  MUNICIPIO_RES  TIPO_PACIENTE  ... OTRO_CASO  \
0           15           15             95              2  ...        99   
1           15            9              2              1  ...         1   
2           16           16            112              1  ...         1   
3           18           18             17              1  ...         2   
4            7            7            101              1  ...         2   

  TOMA_MUESTRA_LAB RESULTADO_LAB  TOMA_MUESTRA_ANTIGENO  RESULTADO_ANTIGENO  \
0                1             2                      2                  97   
1                1             4                      2                  97   
2                1             2                      2                  97   
3                1             2                      2                  97   
4                1             2                      2                  97   

   CLASIFICACION_FINAL  MIGRANTE  PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI  
0                    7        99             México           97    2  
1                    5        99             México           97   97  
2                    7        99             México           97   97  
3                    7        99             México           97   97  
4                    7        99             México           97   97  

[5 rows x 40 columns]

In [ ]:
df.dtypes

FECHA_ACTUALIZACION      object
ID_REGISTRO              object
ORIGEN                    int64
SECTOR                    int64
ENTIDAD_UM                int64
SEXO                      int64
ENTIDAD_NAC               int64
ENTIDAD_RES               int64
MUNICIPIO_RES             int64
TIPO_PACIENTE             int64
FECHA_INGRESO            object
FECHA_SINTOMAS           object
FECHA_DEF                object
INTUBADO                  int64
NEUMONIA                  int64
EDAD                      int64
NACIONALIDAD              int64
EMBARAZO                  int64
HABLA_LENGUA_INDIG        int64
INDIGENA                  int64
DIABETES                  int64
EPOC                      int64
ASMA                      int64
INMUSUPR                  int64
HIPERTENSION              int64
OTRA_COM                  int64
CARDIOVASCULAR            int64
OBESIDAD                  int64
RENAL_CRONICA             int64
TABAQUISMO                int64
OTRO_CASO                 int64
TOMA_MUE

In [ ]:
df.FECHA_ACTUALIZACION.unique()

array(['2021-11-26'], dtype=object)

In [ ]:
df.ORIGEN.unique()

array([1, 2], dtype=int64)

In [ ]:
df['ORIGEN'] = df['ORIGEN'].replace({1: 'USMER',
                                     2: 'FUERA DE USMER'})

In [ ]:
df.SECTOR.unique()

array([12, 13,  6,  3,  8,  9,  4,  5,  2, 11, 10,  7,  1, 99, 14],
      dtype=int64)

In [ ]:
df['SECTOR'] = df['SECTOR'].replace({1: 'CRUZ ROJA',
                                     2: 'DIF',
                                     3: 'ESTATAL',
                                     4: 'IMSS',
                                     5: 'IMSS-BIENESTAR',
                                     6: 'ISSTE',
                                     7: 'MUNICIPAL',
                                     8: 'PEMNEX',
                                     9: 'PRIVADA',
                                     10: 'SEDENA',
                                     11: 'SEMAR',
                                     12: 'SSA',
                                     13: 'UNIVERSITARIO',
                                     14: 'NO ESPECIFICADO',
                                     99: 'NO ESPECIFICADO'})

In [ ]:
df.ENTIDAD_UM.unique()

array([ 9, 16, 18,  7, 19, 13, 29, 27, 31, 12, 22,  2, 26, 32,  1,  4,  8,
       23, 24, 15, 14,  5, 17, 10,  3, 21, 30, 20, 28,  6, 11, 25],
      dtype=int64)

In [ ]:
df['ENTIDAD_UM'] = df['ENTIDAD_UM'].replace({1: 'AGUASCALIENTES',
                                             2: 'BAJA CALIFORNIA',
                                             3: 'BAJA CALIFORNIA SUR',
                                             4: 'CAMPECHE',
                                             5: 'COAHUILA DE ZARAGOZA',
                                             6: 'COLIMA',
                                             7: 'CHIAPAS',
                                             8: 'CHIHUAHUA',
                                             9: 'CIUDAD DE MÉXICO',
                                             10: 'DURANGO',
                                             11: 'GUANAJUATO',
                                             12: 'GUERRERO',
                                             13: 'HIDALGO',
                                             14: 'JALISCO',
                                             15: 'MÉXICO',
                                             16: 'MICHOACÁN DE OCAMPO',
                                             17: 'MORELOS',
                                             18: 'NAYARIT',
                                             19: 'NUEVO LEÓN',
                                             20: 'OAXACA',
                                             21: 'PUEBLA',
                                             22: 'QUERÉTARO',
                                             23: 'QUINTANA ROO',
                                             24: 'SAN LUIS POTOSÍ',
                                             25: 'SINALOA',
                                             26: 'SONORA',
                                             27: 'TABASCO',
                                             28: 'TAMAULIPAS',
                                             29: 'TLAXCALA',
                                             30: 'VERACRUZ DE IGNACIO DE LA LLAVE',
                                             31: 'YUCATÁN',
                                             32: 'ZACATECAS',
                                             36: 'ESTADOS UNIDOS MEXICANOS',
                                             97: 'NO APLICA',
                                             98:'SE IGNORA',
                                             99: 'NO ESPECIFICADO'})

In [ ]:
df.SEXO.unique()

array([2, 1], dtype=int64)

In [ ]:
df['SEXO'] = df['SEXO'].replace({1: 'MUJER',
                                 2: 'HOMBRE',
                                 3: 'NO ESPECIFICADO'})

In [ ]:
df.ENTIDAD_NAC.unique()

array([15, 16, 18,  7,  9, 19, 28, 29, 27, 31, 12,  2, 26, 32, 14, 21,  4,
        8,  1, 24, 23, 10,  5, 17,  3, 30, 25, 22,  6, 11, 13, 20, 99],
      dtype=int64)

In [ ]:
df['ENTIDAD_RES'] = df['ENTIDAD_RES'].replace({1: 'AGUASCALIENTES',
                                               2: 'BAJA CALIFORNIA',
                                               3: 'BAJA CALIFORNIA SUR',
                                               4: 'CAMPECHE',
                                               5: 'COAHUILA DE ZARAGOZA',
                                               6: 'COLIMA',
                                               7: 'CHIAPAS',
                                               8: 'CHIHUAHUA',
                                               9: 'CIUDAD DE MÉXICO',
                                               10: 'DURANGO',
                                               11: 'GUANAJUATO',
                                               12: 'GUERRERO',
                                               13: 'HIDALGO',
                                               14: 'JALISCO',
                                               15: 'MÉXICO',
                                               16: 'MICHOACÁN DE OCAMPO',
                                               17: 'MORELOS',
                                               18: 'NAYARIT',
                                               19: 'NUEVO LEÓN',
                                               20: 'OAXACA',
                                               21: 'PUEBLA',
                                               22: 'QUERÉTARO',
                                               23: 'QUINTANA ROO',
                                               24: 'SAN LUIS POTOSÍ',
                                               25: 'SINALOA',
                                               26: 'SONORA',
                                               27: 'TABASCO',
                                               28: 'TAMAULIPAS',
                                               29: 'TLAXCALA',
                                               30: 'VERACRUZ DE IGNACIO DE LA LLAVE',
                                               31: 'YUCATÁN',
                                               32: 'ZACATECAS',
                                               36: 'ESTADOS UNIDOS MEXICANOS',
                                               97: 'NO APLICA',
                                               98:'SE IGNORA',
                                               99: 'NO ESPECIFICADO'})

In [ ]:
df.ENTIDAD_NAC.unique()

array([15, 16, 18,  7,  9, 19, 28, 29, 27, 31, 12,  2, 26, 32, 14, 21,  4,
        8,  1, 24, 23, 10,  5, 17,  3, 30, 25, 22,  6, 11, 13, 20, 99],
      dtype=int64)

In [ ]:
df['ENTIDAD_NAC'] = df['ENTIDAD_NAC'].replace({1: 'AGUASCALIENTES',
                                               2: 'BAJA CALIFORNIA',
                                               3: 'BAJA CALIFORNIA SUR',
                                               4: 'CAMPECHE',
                                               5: 'COAHUILA DE ZARAGOZA',
                                               6: 'COLIMA',
                                               7: 'CHIAPAS',
                                               8: 'CHIHUAHUA',
                                               9: 'CIUDAD DE MÉXICO',
                                               10: 'DURANGO',
                                               11: 'GUANAJUATO',
                                               12: 'GUERRERO',
                                               13: 'HIDALGO',
                                               14: 'JALISCO',
                                               15: 'MÉXICO',
                                               16: 'MICHOACÁN DE OCAMPO',
                                               17: 'MORELOS',
                                               18: 'NAYARIT',
                                               19: 'NUEVO LEÓN',
                                               20: 'OAXACA',
                                               21: 'PUEBLA',
                                               22: 'QUERÉTARO',
                                               23: 'QUINTANA ROO',
                                               24: 'SAN LUIS POTOSÍ',
                                               25: 'SINALOA',
                                               26: 'SONORA',
                                               27: 'TABASCO',
                                               28: 'TAMAULIPAS',
                                               29: 'TLAXCALA',
                                               30: 'VERACRUZ DE IGNACIO DE LA LLAVE',
                                               31: 'YUCATÁN',
                                               32: 'ZACATECAS',
                                               36: 'ESTADOS UNIDOS MEXICANOS',
                                               97: 'NO APLICA',
                                               98:'SE IGNORA',
                                               99: 'NO ESPECIFICADO'})

In [ ]:
df.TIPO_PACIENTE.unique()

array([2, 1], dtype=int64)

In [ ]:
df['TIPO_PACIENTE'] = df['TIPO_PACIENTE'].replace({1: 'AMBULATORIO',
                                                   2: 'HOSPITALIZADO',
                                                   3: 'NO ESPECIFICADO'})

In [ ]:
df.INTUBADO.unique()

array([ 1, 97,  2, 99], dtype=int64)

In [ ]:
df['INTUBADO'] = df['INTUBADO'].replace({1: 'SI',
                                         2: 'NO',
                                         97: 'NO APLICA',
                                         99:'NO ESPECIFICADO'})

In [ ]:
df.NEUMONIA.unique()

array([ 1,  2, 99], dtype=int64)

In [ ]:
df['NEUMONIA'] = df['INTUBADO'].replace({1: 'SI',
                                         2: 'NO',
                                         99:'NO ESPECIFICADO'})

In [ ]:
df.NACIONALIDAD.unique()

array([1, 2], dtype=int64)

In [ ]:
df['NACIONALIDAD'] = df['NACIONALIDAD'].replace({1: 'MEXICANA',
                                                 2: 'EXTRANJERO',
                                                 99:'NO ESPECIFICADO'})

In [ ]:
df.EMBARAZO.unique()

array([97,  2,  1, 98, 99], dtype=int64)

In [ ]:
df['EMBARAZO'] = df['EMBARAZO'].replace({1: 'SI',
                                         2: 'NO',
                                         97:'NO APLICA',
                                         98:'SE IGNORA',
                                         99:'NO ESPECIFICADO'})

In [ ]:
df.HABLA_LENGUA_INDIG.unique()

array([ 2, 99,  1], dtype=int64)

In [ ]:
df['HABLA_LENGUA_INDIG'] = df['HABLA_LENGUA_INDIG'].replace({1: 'SI',
                                                             2: 'NO',
                                                             99:'NO ESPECIFICADO'})

In [ ]:
df.INDIGENA.unique()

array([ 2, 99,  1], dtype=int64)

In [ ]:
df['INDIGENA'] = df['INDIGENA'].replace({1: 'SI',
                                         2: 'NO',
                                         99:'NO ESPECIFICADO'})

In [ ]:
df.DIABETES.unique()

array([ 2,  1, 98], dtype=int64)

In [ ]:
df['DIABETES'] = df['DIABETES'].replace({1: 'SI',
                                         2: 'NO',
                                         98:'SE IGNORA'})

In [ ]:
df.EPOC.unique()

array([ 2,  1, 98], dtype=int64)

In [ ]:
df['EPOC'] = df['EPOC'].replace({1: 'SI',
                                 2: 'NO',
                                 98:'SE IGNORA'})

In [ ]:
df.ASMA.unique()

array([ 2,  1, 98], dtype=int64)

In [ ]:
df['ASMA']=df['ASMA'].replace({1: 'SI',
                               2: 'NO',
                               98:'SE IGNORA'})

In [ ]:
df.INMUSUPR.unique()

array([ 2, 98,  1], dtype=int64)

In [ ]:
df['INMUSUPR']=df['INMUSUPR'].replace({1: 'SI',
                                       2: 'NO',
                                       98:'SE IGNORA'})

In [ ]:
df.HIPERTENSION.unique()

array([ 2,  1, 98], dtype=int64)

In [ ]:
df['HIPERTENSION']=df['HIPERTENSION'].replace({1: 'SI',
                                               2: 'NO',
                                               98: 'SE IGNORA'})

In [ ]:
df.OTRA_COM.unique()

array([ 2,  1, 98], dtype=int64)

In [ ]:
df['OTRA_COM']=df['OTRA_COM'].replace({1: 'SI',
                                       2: 'NO',
                                       98: 'SE IGNORA'})

In [ ]:
df.CARDIOVASCULAR.unique()

array([ 2, 98,  1], dtype=int64)

In [ ]:
df['CARDIOVASCULAR']=df['CARDIOVASCULAR'].replace({1: 'SI',
                                                   2: 'NO',
                                                   98: 'SE IGNORA'})

In [ ]:
df.OBESIDAD.unique()

array([ 2,  1, 98], dtype=int64)

In [ ]:
df['OBESIDAD'] = df['OBESIDAD'].replace({1: 'SI',
                                         2: 'NO',
                                         98:'SE IGNORA'})

In [ ]:
df.RENAL_CRONICA.unique()

array([ 2, 98,  1], dtype=int64)

In [ ]:
df['RENAL_CRONICA'] = df['RENAL_CRONICA'].replace({1: 'SI',
                                                   2: 'NO',
                                                   98:'SE IGNORA'})

In [ ]:
df.TABAQUISMO.unique()

array([ 1,  2, 98], dtype=int64)

In [ ]:
df['TABAQUISMO'] = df['TABAQUISMO'].replace({1: 'SI',
                                             2: 'NO',
                                             98:'SE IGNORA'})

In [ ]:
df.OTRO_CASO.unique()

array([99,  1,  2], dtype=int64)

In [ ]:
df['OTRO_CASO'] = df['OTRO_CASO'].replace({1: 'SI',
                                           2: 'NO',
                                           99:'NO ESPECIFICADO'})

In [ ]:
df.TOMA_MUESTRA_LAB.unique()

array([1, 2], dtype=int64)

In [ ]:
df['TOMA_MUESTRA_LAB'] = df['TOMA_MUESTRA_LAB'].replace({1: 'SI',
                                                         2: 'NO'})

In [ ]:
df.RESULTADO_LAB.unique()

array([ 2,  4, 97,  1,  3], dtype=int64)

In [ ]:
df['RESULTADO_LAB'] = df['RESULTADO_LAB'].replace({1: 'POSITIVO A SARS-COV-2',
                                     2: 'NO POSITIVO A SARS-COV-2',
                                     3:'RESULTADO PENDIENTE',
                                     4:'RESULTADO NO ADECUADO',
                                     97:'NO APLICA(CASO SIN MUESTRA)',})

In [ ]:
df.TOMA_MUESTRA_ANTIGENO.unique()

array([2, 1], dtype=int64)

In [ ]:
df['TOMA_MUESTRA_ANTIGENO']=df['TOMA_MUESTRA_ANTIGENO'].replace({1: 'SI',
                                                                 2: 'NO'})

In [ ]:
df.RESULTADO_ANTIGENO.unique()

array([97,  1,  2], dtype=int64)

In [ ]:
df['RESULTADO_ANTIGENO']=df['RESULTADO_ANTIGENO'].replace({1: 'POSITIVO A SARS-COV-2',
                                                           2: 'NEGATIVO A SARS-COV-2',
                                                           97: 'NO APLICA (CASO SIN MUESTRA)'})

In [ ]:
df.CLASIFICACION_FINAL.unique()

array([7, 5, 3, 6, 1, 2, 4], dtype=int64)

In [ ]:
df['CLASIFICACION_FINAL']=df['CLASIFICACION_FINAL'].replace({1: 'CASO DE COVID-19 CONFIRMADO POR ASOCIACIÓN CLÍNICA EPIDEMIOLÓGICA',
                                                             2: 'CASO DE COVID-19 CONFIRMADO POR COMITÉ DE DICTAMINACIÓN',
                                                             3: 'CASO DE SARS-COV-2 CONFIRMADO',
                                                             4: 'INVÁLIDO POR LABORATORIO',
                                                             5: 'NO REALIZADO POR LABORATORIO',
                                                             6: 'CASO SOSPECHOSO',
                                                             7: 'NEGATIVO A SARS-COV-2'})

In [ ]:
df.MIGRANTE.unique()

array([99,  2,  1], dtype=int64)

In [ ]:
df['MIGRANTE']=df['MIGRANTE'].replace({1: 'SI',
                                       2: 'NO',
                                       99: 'NO ESPECIFICADO'})

In [ ]:
df.UCI.unique()

array([ 2, 97,  1, 99], dtype=int64)

In [ ]:
df['UCI']=df['UCI'].replace({1: 'SI',
                             2: 'NO',
                             97: 'NO APLICA',
                             99: 'NO ESPECIFICADO'})

In [ ]:
df.head()

FECHA_ACTUALIZACION ID_REGISTRO          ORIGEN SECTOR           ENTIDAD_UM  \
0          2021-11-26      z4e838           USMER    SSA     CIUDAD DE MÉXICO   
1          2021-11-26      z2b144  FUERA DE USMER    SSA     CIUDAD DE MÉXICO   
2          2021-11-26      zz7202           USMER    SSA  MICHOACÁN DE OCAMPO   
3          2021-11-26      z58ed3  FUERA DE USMER    SSA              NAYARIT   
4          2021-11-26      z3be8c  FUERA DE USMER    SSA              CHIAPAS   

     SEXO          ENTIDAD_NAC          ENTIDAD_RES  MUNICIPIO_RES  \
0  HOMBRE               MÉXICO               MÉXICO             95   
1   MUJER               MÉXICO     CIUDAD DE MÉXICO              2   
2  HOMBRE  MICHOACÁN DE OCAMPO  MICHOACÁN DE OCAMPO            112   
3   MUJER              NAYARIT              NAYARIT             17   
4   MUJER              CHIAPAS              CHIAPAS            101   

   TIPO_PACIENTE  ...        OTRO_CASO TOMA_MUESTRA_LAB  \
0  HOSPITALIZADO  ...  NO ESPECIFICADO               SI   
1    AMBULATORIO  ...               SI               SI   
2    AMBULATORIO  ...               SI               SI   
3    AMBULATORIO  ...               NO               SI   
4    AMBULATORIO  ...               NO               SI   

              RESULTADO_LAB TOMA_MUESTRA_ANTIGENO  \
0  NO POSITIVO A SARS-COV-2                    NO   
1     RESULTADO NO ADECUADO                    NO   
2  NO POSITIVO A SARS-COV-2                    NO   
3  NO POSITIVO A SARS-COV-2                    NO   
4  NO POSITIVO A SARS-COV-2                    NO   

             RESULTADO_ANTIGENO           CLASIFICACION_FINAL  \
0  NO APLICA (CASO SIN MUESTRA)         NEGATIVO A SARS-COV-2   
1  NO APLICA (CASO SIN MUESTRA)  NO REALIZADO POR LABORATORIO   
2  NO APLICA (CASO SIN MUESTRA)         NEGATIVO A SARS-COV-2   
3  NO APLICA (CASO SIN MUESTRA)         NEGATIVO A SARS-COV-2   
4  NO APLICA (CASO SIN MUESTRA)         NEGATIVO A SARS-COV-2   

          MIGRANTE PAIS_NACIONALIDAD PAIS_ORIGEN        UCI  
0  NO ESPECIFICADO            México          97         NO  
1  NO ESPECIFICADO            México          97  NO APLICA  
2  NO ESPECIFICADO            México          97  NO APLICA  
3  NO ESPECIFICADO            México          97  NO APLICA  
4  NO ESPECIFICADO            México          97  NO APLICA  

[5 rows x 40 columns]

In [ ]:
df.to_csv('sars-cov2.csv', header=False, index=False)

KeyboardInterrupt: 